### ISSUE TITLE
Package structure for publishing - Split into two or as single package?

### ISSUE THREAD

**Issue by ben1post** [ben1post/phydra#2]
Currently, the repository contains:

- Backend code to create "_Components_" of ordinary differential equation based models, as an extension of [xarray-simlab](https://github.com/benbovy/xarray-simlab).
- A library of _Components_ and example models that are domain-specific to marine ecosystem modelling

Perhaps it would make sense to split this code base into two packages, to advertise the backend structure (that is not domain specific, but could be used for any ODE based models) to users outside the marine ecosystem modelling domain.

The backend code could be put into a package called for example "_xarray-simlab-ode_", "_xsimlab-ode_" or "_xarray-odelab_", to clearly state the general applicability. Domain specific code could then make use of that package and be distributed as _phydra_.

Before deciding on this, I would be very interested in your thoughts on the matter @benbovy, as I do not want to use a name derived from your own package without your support or consent.

**Comment by benbovy** [comment]
I guess that splitting the backend and the marine ecosystem code makes sense if you (or other potential users) want to eventually reuse the backend for other purposes.

Splitting the code into two packages is more maintenance work if the code is relatively small and tightly integrated. But it will turn into less maintenance burden as the codebase grows and become used for various purposes.

I don't mind at all that you choose one of the names above for the backend. As it is built on top of xarray-simlab, it would be great if the API of the backend doesn't "hide" the underlying API provided by xarray-simlab (i.e., user may use and mix API from both xarray-simlab and ODE backend without confusion), but looking briefly through the code I think that's already the case, since most of the ODE backend API consist of factory functions for xarray-simlab variables, processes and models.

**Comment by ben1post** [comment]
I have split the code into this repository with jupyter notebooks and the model code, and [a separate repository](https://github.com/ben1post/xarray-simlab-ode/tree/main) for the package `xso`, the extension of Xarray-simlab to build ODE-based models.
